In [5]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a[-1]

np.int64(4)

In [9]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[-1:5]

array([], dtype=int64)

In [11]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b[0]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
d

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [16]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
c=np.array([13,14,15])
d=np.concatenate((a,c))

In [18]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [19]:
np.where(d==4)

(array([3]),)

In [20]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [21]:
c=np.array([3,4,2,10,5])
np.sort(c)


array([ 2,  3,  4,  5, 10])

In [25]:
c=np.array([[2,3,1,6],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 6],
       [1, 2, 4, 5]])

In [26]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [27]:
np.random.randint(100)

98

In [28]:
np.random.rand(10)


array([0.24989968, 0.28397074, 0.38503102, 0.05214929, 0.39300056,
       0.30541961, 0.46787579, 0.46899361, 0.08413313, 0.97905589])

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones(2)

array([1., 1.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])